# container oficial do python (ambiente)
FROM python

# pasta no container
WORKDIR /app

# copia todos os arquivos da pasta para /app, no container
COPY . /app

# comando a ser executado no container
CMD [ "python", "rng.py" ]


