import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'prontuario';

  contentText = `Lorem Ipsum
  "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
  "There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis lectus rhoncus, consectetur libero ac, efficitur nisl. In vel urna scelerisque nulla mollis euismod. In feugiat orci massa, ut tincidunt odio fermentum eget. Suspendisse efficitur nulla in consectetur vulputate. Nulla facilisi. Aliquam erat volutpat. Nam suscipit interdum libero ac interdum. Vivamus ullamcorper, justo et venenatis vehicula, dolor tellus ultrices sapien, at accumsan purus mauris et eros. Integer non pulvinar magna, ac hendrerit mi. Nulla molestie mi enim, a lacinia urna ornare at. Vivamus tortor orci, placerat sit amet tempus eget, lobortis ut metus. Etiam tincidunt purus quis dapibus volutpat.

  Nullam lobortis, erat sit amet sagittis condimentum, lectus metus egestas nisi, id convallis felis purus ac elit. Phasellus at venenatis tellus. Pellentesque euismod, orci eget auctor malesuada, tortor tortor efficitur felis, vitae feugiat ex elit sit amet magna. Maecenas tincidunt semper nunc, ac faucibus mi ultrices ut. Aenean eget tellus id urna congue aliquam sit amet a tortor. Ut ullamcorper eleifend tincidunt. Vestibulum vitae interdum massa, et fermentum justo. Donec vel enim nulla. Cras vel tristique ante. Quisque sed aliquam ex. Sed non ante nibh. Suspendisse ut varius tellus. Morbi sit amet arcu at metus tincidunt imperdiet.

  Donec aliquet tempus nulla vel euismod. Nulla congue lacus felis, eu mollis justo interdum ac. Fusce quis vestibulum felis. Vestibulum nec justo lorem. Sed ultricies odio faucibus erat pellentesque eleifend. Suspendisse potenti. Pellentesque gravida varius mauris id sollicitudin. Aliquam erat volutpat. Praesent sed congue sapien, vel tincidunt ante.

  Duis eget lacus lacus. Phasellus nec purus posuere magna pretium vulputate. Cras eu facilisis magna. Mauris eleifend magna mauris, sit amet congue massa porttitor in. Fusce scelerisque justo volutpat mauris consectetur posuere. Vestibulum massa mi, consequat id nisl dapibus, volutpat gravida ante. Phasellus semper luctus vulputate. Duis lobortis dignissim nunc, nec bibendum magna aliquam eget. Etiam commodo eros vitae turpis aliquet, sed dignissim nisi tempor. Vestibulum finibus ut tellus ultricies posuere. Donec consectetur vehicula turpis, egestas fermentum sapien interdum vel. Etiam feugiat ante lectus, sit amet fringilla velit tempor nec. Nam vulputate turpis et ante efficitur, vel tincidunt diam finibus. Suspendisse finibus venenatis condimentum.

  Pellentesque ut cursus diam. In ut tortor pellentesque, ornare nunc quis, pulvinar mauris. Phasellus aliquet elementum egestas. Aliquam erat volutpat. In hac habitasse platea dictumst. Mauris pretium tincidunt semper. Nam eget ex nec purus aliquet scelerisque. Ut eget risus et metus luctus mollis. Proin convallis lacus nec pulvinar sodales. Quisque lobortis pulvinar sapien quis feugiat. Donec scelerisque libero eget ante vulputate mollis a at ante. Aliquam cursus convallis enim sit amet pellentesque. Nulla non tortor dictum, dictum tellus sed, faucibus augue. Integer elementum leo quis porta volutpat.

  Aenean lectus eros, mattis ac orci et, auctor lobortis sapien. Nam metus risus, auctor imperdiet porta convallis, posuere et nunc. Duis sodales magna magna. Aenean tempus porttitor sem, vitae dapibus ante euismod sed. Nulla rutrum eros id enim lacinia dignissim. Morbi ac diam nisi. Aliquam egestas enim sed sem posuere, a imperdiet nibh consectetur. Nam ullamcorper magna eu magna pellentesque luctus. Sed mauris nibh, posuere eget bibendum et, facilisis id massa. Nulla volutpat a neque accumsan laoreet. Nulla elementum gravida elit.

  Fusce suscipit rutrum leo vel porttitor. Curabitur porta sagittis augue sed fringilla. Suspendisse varius nisl turpis. Aliquam eleifend ante quis gravida efficitur. Proin semper, lacus vel vehicula posuere, metus arcu varius sapien, eu eleifend nunc ex quis massa. Fusce vulputate tempor sem, in scelerisque purus. In a vulputate mauris. Ut maximus, purus eu convallis fringilla, libero neque molestie dolor, eu laoreet tortor risus at turpis. Donec at enim est. Curabitur elementum justo tristique auctor porttitor. Integer dui velit, varius vel condimentum at, vestibulum eu diam.

  Nulla neque turpis, interdum sit amet auctor sed, pretium at metus. Proin feugiat turpis sit amet nunc congue scelerisque. Nam vitae aliquam ligula. Nullam laoreet consectetur hendrerit. Ut dui nisl, suscipit in cursus in, convallis nec lacus. Phasellus congue risus et efficitur bibendum. Nam porttitor nibh porttitor ultricies aliquam. In sed lobortis turpis. Suspendisse nulla purus, hendrerit vitae placerat vel, ullamcorper eu sem. Sed arcu massa, volutpat et nisl sit amet, tempor placerat tellus. Morbi finibus, justo id scelerisque elementum, massa est laoreet magna, mollis aliquam quam mauris in urna. Ut porttitor erat sit amet euismod pretium. Morbi hendrerit purus mi, non tempus ex malesuada eget.

  In commodo viverra massa nec porta. Duis tincidunt mollis pharetra. Praesent egestas lacus in turpis vestibulum, at luctus est commodo. Aliquam tincidunt facilisis libero eget blandit. Praesent egestas, nibh non porta euismod, metus risus suscipit urna, at auctor metus quam eget ligula. Vivamus eu turpis id velit ultrices molestie. Duis turpis elit, rutrum eu placerat a, gravida vestibulum elit. Sed feugiat magna nec mi rutrum, non dignissim arcu elementum. Proin sagittis placerat libero, eget finibus dui convallis et. Mauris fermentum bibendum ante, sit amet tincidunt enim accumsan non. Suspendisse eget rutrum nisl. Vivamus tincidunt accumsan velit, ac mollis nisi volutpat a.

  Etiam maximus convallis nulla, et dapibus dolor. Duis fringilla lectus arcu, nec scelerisque ex luctus ut. Cras id pharetra quam. Pellentesque ac condimentum nibh. Vestibulum ultrices molestie consequat. Nunc condimentum a dui vel congue. Ut et dolor quis nulla dignissim posuere non in dolor. Proin ultrices lorem rutrum nunc cursus, sit amet suscipit quam blandit. Etiam convallis laoreet ipsum, quis varius lorem posuere eu. Cras fringilla dolor tortor, id ullamcorper metus accumsan id.

  Quisque eu semper odio. Suspendisse auctor, nisl nec vestibulum lobortis, metus tortor luctus metus, ut fermentum odio enim pharetra sapien. Sed sed convallis augue. Vestibulum vitae felis elit. Donec non ultrices enim. Mauris dignissim vehicula ex, in consequat mi hendrerit a. Proin consectetur justo porta nunc gravida convallis. Vivamus eleifend accumsan purus.

  Aliquam vel fermentum nunc, vel pulvinar dui. Aliquam eget risus at massa blandit accumsan sit amet fringilla sapien. Nam ipsum nisi, finibus nec rutrum ac, vulputate nec urna. Nulla vehicula magna tellus, eu dictum dui sollicitudin ut. Duis varius, elit quis vestibulum pulvinar, mi sem ultricies nisl, sed vulputate nulla dolor id ante. Sed eu viverra arcu. Donec cursus ligula eget ligula imperdiet, ut interdum ligula elementum. Ut sem risus, fermentum sed semper a, laoreet ac quam. Duis imperdiet elit non eros aliquet, et scelerisque sapien viverra. In a libero dui. Ut malesuada risus at iaculis mattis. Pellentesque nec molestie elit. Mauris ac orci massa. Donec ac purus mattis, interdum massa nec, laoreet urna. Quisque eget nisl mollis, facilisis odio et, pulvinar dolor. Nunc at neque eu nibh ornare volutpat.

  Maecenas sit amet turpis non massa gravida pellentesque sit amet at enim. Maecenas tincidunt pulvinar nulla. Vestibulum vel urna leo. Sed eget ligula eget massa fringilla auctor. Ut sed posuere risus. Cras dictum quis tellus at vulputate. Fusce ut convallis ex.

  Fusce in turpis vitae quam lobortis lobortis. Ut lorem nisi, tincidunt ut eleifend ac, semper eu diam. Praesent eu felis ac nibh mollis finibus in in ex. Pellentesque quis volutpat sem. Aenean tincidunt lacinia nunc ut dignissim. Vestibulum commodo ultrices tristique. Nulla semper ultricies tincidunt. Sed lorem ipsum, tempor quis odio vitae, rhoncus pulvinar metus. Phasellus et maximus massa. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi molestie sapien a justo commodo blandit. In cursus lectus nec massa iaculis ullamcorper. Donec sed purus quis diam iaculis bibendum. Etiam consectetur, justo vel gravida ullamcorper, diam ex condimentum risus, eu cursus nisl erat sit amet leo. Sed a purus arcu.

  Sed a nunc pellentesque ex porttitor ullamcorper a ut lectus. Sed sed est eu lacus tempor commodo et vel enim. Mauris velit quam, ultricies ultricies ex feugiat, placerat euismod elit. Nam aliquam ante nisl, eu placerat metus pulvinar nec. Donec nunc lectus, blandit non sagittis a, facilisis eget lorem. Ut ut fermentum sem. Duis nec sapien ipsum. Nulla pulvinar sapien a tellus eleifend elementum quis sit amet quam. Integer et mauris eget urna placerat maximus. Donec ut ipsum interdum, suscipit eros a, pretium arcu. Nunc hendrerit magna bibendum lacus rutrum, sed convallis felis pretium. Nunc finibus fermentum dolor ut ultrices. Curabitur pulvinar finibus accumsan. Aliquam erat volutpat.

  Praesent eu lorem imperdiet, lobortis augue eget, aliquet dolor. Nullam nec mauris eu mi blandit sollicitudin. Donec sagittis arcu ac ullamcorper sollicitudin. Nam volutpat orci porttitor posuere tempor. Duis vel augue iaculis, sollicitudin justo sit amet, ultricies diam. Curabitur quis lacus at eros mattis mattis ut a leo. Mauris quis justo vehicula, gravida mauris ac, ornare sem. Nam tempus arcu vitae dolor tempor congue. Maecenas laoreet urna efficitur, pretium augue nec, tempor mi. Maecenas ac ipsum gravida, cursus ligula non, egestas massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

  Curabitur pharetra efficitur mauris a rhoncus. Nulla scelerisque nulla a rhoncus bibendum. Etiam sit amet turpis vitae justo consectetur hendrerit eget ullamcorper ante. Nunc iaculis gravida nulla. Integer finibus quam in facilisis vulputate. Nullam elementum gravida ornare. Fusce quis purus egestas, commodo sem id, auctor turpis.

  Aenean molestie ex non vulputate congue. Suspendisse at mattis libero, eu dapibus turpis. Morbi lacinia lectus a magna laoreet pharetra. Morbi at scelerisque ante. Sed venenatis mattis libero quis fringilla. Nullam at leo velit. Nunc pulvinar massa quis magna vehicula laoreet. Donec finibus nisi urna, eu aliquam orci sagittis eu. Pellentesque eget enim congue, egestas lorem sit amet, pretium elit. Sed sodales tortor arcu, vitae malesuada risus laoreet id. Fusce quis diam dui.

  Aenean nec nibh quis turpis lobortis auctor. Nulla non vestibulum arcu, sit amet dapibus tortor. Duis tempus ex id libero condimentum accumsan. Sed sit amet lacus quam. Vivamus in aliquet sem. Proin ut lacus metus. Fusce nec blandit enim. Suspendisse aliquet eleifend metus et ultrices. Proin pellentesque sapien a blandit aliquam. Vestibulum tempor, eros a varius luctus, odio nibh venenatis lacus, in pharetra ante felis non nisl.

  Aenean varius tellus vel purus eleifend, non fermentum nulla auctor. Morbi elit nisl, tincidunt non erat vel, sagittis placerat ante. Praesent a sagittis diam. Phasellus eu blandit odio. Duis vel gravida diam, vitae tempor nisl. Vivamus eget ornare dolor. Aenean id massa a massa tempor facilisis. Vivamus pharetra turpis eget dui imperdiet interdum eget vitae libero. Etiam porttitor lacus vitae erat sagittis, at commodo mauris fermentum. Nam rutrum nisi est, id sollicitudin justo gravida vitae. Quisque vitae justo luctus ante suscipit semper quis porta odio. Proin elementum a odio ut venenatis. Sed imperdiet nec urna non gravida. Nullam semper bibendum viverra. Sed non placerat justo, eget blandit libero.

  Duis non arcu ornare enim semper eleifend vitae vel eros. Nunc placerat elit eu porttitor ultrices. Sed blandit ex lectus, a pharetra enim tempus et. Etiam gravida tristique pulvinar. Duis mattis eros ac mi luctus hendrerit. Etiam tempor, orci eu vulputate dictum, ligula purus sagittis nibh, convallis sagittis felis velit eget turpis. Suspendisse a volutpat nulla. Cras mi risus, fermentum non magna aliquet, consectetur porttitor erat.

  Sed eget maximus lorem. Pellentesque cursus hendrerit urna, ac venenatis quam aliquet interdum. Proin ornare dapibus elit, non faucibus urna. Morbi ultrices sit amet diam ut tristique. Morbi ornare elit sed turpis rutrum, quis pulvinar eros laoreet. Sed ac suscipit tortor, vel elementum risus. Nunc commodo elementum felis dictum auctor. Nam vel ante eu libero pellentesque eleifend. Aliquam in turpis porttitor, congue nunc ac, aliquam est. Sed posuere nibh sem, egestas rhoncus nibh dictum quis. Donec posuere dui in posuere venenatis. Duis nibh diam, iaculis sed ultrices eleifend, bibendum at ante. Nam vitae nisl quis urna molestie scelerisque. Morbi velit arcu, sagittis quis est a, posuere elementum elit.

  Vestibulum non iaculis urna, at convallis tellus. Duis ullamcorper pharetra faucibus. Proin at augue leo. Vestibulum placerat egestas quam vel tempor. Nullam sollicitudin elementum nisi, luctus blandit nulla luctus vitae. Cras elementum odio et nulla ullamcorper tempor. Pellentesque hendrerit ultricies nunc sed euismod. Nulla nec luctus elit, non aliquam nunc. Nunc at magna at nunc sodales accumsan non eu nisi. Proin eget dignissim massa.

  Donec eu massa lectus. Proin vitae leo sit amet est pulvinar egestas at a nibh. Etiam imperdiet porttitor elementum. Fusce luctus hendrerit erat, ac finibus enim tristique id. Quisque interdum imperdiet tellus ut bibendum. Praesent vulputate, nunc quis sollicitudin pharetra, enim purus tempor ante, et imperdiet lorem ipsum ac risus. Quisque id pretium eros. Vivamus ante lectus, ornare ut ex et, ornare varius diam. Aliquam scelerisque congue mauris et egestas. Phasellus tincidunt viverra massa a fringilla. Fusce at lorem at nisi accumsan elementum eget et lacus. Maecenas et porta ligula.

  Aliquam gravida dapibus venenatis. Nulla condimentum, nisl sit amet faucibus tempus, nulla enim convallis massa, vitae finibus mauris felis scelerisque enim. Duis lobortis elit eget felis varius, non tincidunt ligula vulputate. Ut quam massa, egestas sed dapibus vel, interdum in ex. Fusce tincidunt ultricies elit, vel imperdiet eros interdum id. Morbi turpis nunc, congue eu elit at, ultrices hendrerit metus. Nulla varius nunc ac lorem molestie porttitor. Sed erat nisi, malesuada id lacus sit amet, pellentesque suscipit augue. Pellentesque maximus eleifend massa, sed hendrerit est fermentum vel. Sed dapibus massa in mauris bibendum, eget hendrerit lectus vehicula.

  Nunc quis feugiat massa. Ut at enim ut felis lacinia fringilla at eu risus. Sed eget tempor nisl. Phasellus consectetur est eget enim suscipit tincidunt. Sed gravida accumsan nibh id scelerisque. Fusce id nisi erat. Nam eget lacus et ante accumsan vulputate eu eget neque. Morbi mollis pellentesque enim eu venenatis. In eget purus erat. Aliquam condimentum volutpat mattis. Phasellus suscipit ultricies ipsum. Duis a metus mauris.

  Nullam augue dui, tempus consequat lacinia quis, volutpat id nibh. Proin lorem risus, dictum non sem mollis, dictum pretium lorem. Nunc tristique, nisl vel mattis venenatis, erat velit accumsan ipsum, vel luctus nibh ante condimentum diam. Morbi interdum tempor feugiat. In hac habitasse platea dictumst. Cras quis tincidunt dui, ac iaculis est. Nullam porttitor pharetra turpis, feugiat luctus tellus rhoncus eget. Nunc eget augue odio.

  Nunc eget vestibulum nisl. Nunc mauris diam, tempor quis turpis ac, rutrum lacinia nulla. Proin eu laoreet eros. Praesent eu malesuada ex. Integer eget justo ac elit rutrum imperdiet et eget mi. Donec placerat erat nec ligula luctus, a bibendum sem condimentum. In egestas neque cursus, auctor nisl at, suscipit erat.

  Curabitur enim mauris, suscipit sed mi sit amet, euismod tristique eros. Vivamus tempor fermentum vulputate. Donec sollicitudin mauris dolor, nec eleifend odio tincidunt a. Nulla ut sagittis leo. Nullam quis semper risus, eu tincidunt lacus. Maecenas molestie nisi quis sem varius malesuada. Mauris et sem ante. Etiam in ipsum leo. Nullam sit amet elit cursus, tincidunt odio non, sagittis orci.

  Curabitur ut quam sollicitudin, mollis ipsum vitae, egestas quam. Cras ullamcorper nisi eget felis egestas condimentum. Integer vulputate vestibulum elementum. Quisque magna quam, sagittis in mi id, auctor varius nisl. Phasellus pretium quis augue eget volutpat. Proin sit amet diam eget dolor tristique iaculis vitae in lectus. Fusce consequat ultricies sapien ut accumsan. Vivamus commodo lectus nec est pharetra vehicula. Quisque ullamcorper aliquet elementum. Nulla sagittis, ante eu consequat varius, urna tortor auctor ante, vitae imperdiet tellus lacus sit amet est. Vivamus luctus hendrerit lacus, ut suscipit augue ornare eu. Proin aliquam elit ac gravida rhoncus.`;

  imgLink =
    'https://upload.wikimedia.org/wikipedia/commons/6/63/IMG_%28business%29.svg';

    contentText2 = `Lorem Ipsum
  "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
  "There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis lectus rhoncus, consectetur libero ac, efficitur nisl. In vel urna scelerisque nulla mollis euismod. In feugiat orci massa, ut tincidunt odio fermentum eget. Suspendisse efficitur nulla in consectetur vulputate. Nulla facilisi. Aliquam erat volutpat. Nam suscipit interdum libero ac interdum. Vivamus ullamcorper, justo et venenatis vehicula, dolor tellus ultrices sapien, at accumsan purus mauris et eros. Integer non pulvinar magna, ac hendrerit mi. Nulla molestie mi enim, a lacinia urna ornare at. Vivamus tortor orci, placerat sit amet tempus eget, lobortis ut metus. Etiam tincidunt purus quis dapibus volutpat.

  Nullam lobortis, erat sit amet sagittis condimentum, lectus metus egestas nisi, id convallis felis purus ac elit. Phasellus at venenatis tellus. Pellentesque euismod, orci eget auctor malesuada, tortor tortor efficitur felis, vitae feugiat ex elit sit amet magna. Maecenas tincidunt semper nunc, ac faucibus mi ultrices ut. Aenean eget tellus id urna congue aliquam sit amet a tortor. Ut ullamcorper eleifend tincidunt. Vestibulum vitae interdum massa, et fermentum justo. Donec vel enim nulla. Cras vel tristique ante. Quisque sed aliquam ex. Sed non ante nibh. Suspendisse ut varius tellus. Morbi sit amet arcu at metus tincidunt imperdiet.

  Donec aliquet tempus nulla vel euismod. Nulla congue lacus felis, eu mollis justo interdum ac. Fusce quis vestibulum felis. Vestibulum nec justo lorem. Sed ultricies odio faucibus erat pellentesque eleifend. Suspendisse potenti. Pellentesque gravida varius mauris id sollicitudin. Aliquam erat volutpat. Praesent sed congue sapien, vel tincidunt ante.

  Duis eget lacus lacus. Phasellus nec purus posuere magna pretium vulputate. Cras eu facilisis magna. Mauris eleifend magna mauris, sit amet congue massa porttitor in. Fusce scelerisque justo volutpat mauris consectetur posuere. Vestibulum massa mi, consequat id nisl dapibus, volutpat gravida ante. Phasellus semper luctus vulputate. Duis lobortis dignissim nunc, nec bibendum magna aliquam eget. Etiam commodo eros vitae turpis aliquet, sed dignissim nisi tempor. Vestibulum finibus ut tellus ultricies posuere. Donec consectetur vehicula turpis, egestas fermentum sapien interdum vel. Etiam feugiat ante lectus, sit amet fringilla velit tempor nec. Nam vulputate turpis et ante efficitur, vel tincidunt diam finibus. Suspendisse finibus venenatis condimentum.

  Pellentesque ut cursus diam. In ut tortor pellentesque, ornare nunc quis, pulvinar mauris. Phasellus aliquet elementum egestas. Aliquam erat volutpat. In hac habitasse platea dictumst. Mauris pretium tincidunt semper. Nam eget ex nec purus aliquet scelerisque. Ut eget risus et metus luctus mollis. Proin convallis lacus nec pulvinar sodales. Quisque lobortis pulvinar sapien quis feugiat. Donec scelerisque libero eget ante vulputate mollis a at ante. Aliquam cursus convallis enim sit amet pellentesque. Nulla non tortor dictum, dictum tellus sed, faucibus augue. Integer elementum leo quis porta volutpat.

  Aenean lectus eros, mattis ac orci et, auctor lobortis sapien. Nam metus risus, auctor imperdiet porta convallis, posuere et nunc. Duis sodales magna magna. Aenean tempus porttitor sem, vitae dapibus ante euismod sed. Nulla rutrum eros id enim lacinia dignissim. Morbi ac diam nisi. Aliquam egestas enim sed sem posuere, a imperdiet nibh consectetur. Nam ullamcorper magna eu magna pellentesque luctus. Sed mauris nibh, posuere eget bibendum et, facilisis id massa. Nulla volutpat a neque accumsan laoreet. Nulla elementum gravida elit.
nisi eget felis egestas condimentum. Integer vulputate vestibulum elementum. Quisque magna quam, sagittis in mi id, auctor varius nisl. Phasellus pretium quis augue eget volutpat. Proin sit amet diam eget dolor tristique iaculis vitae in lectus. Fusce consequat ultricies sapien ut accumsan. Vivamus commodo lectus nec est pharetra vehicula. Quisque ullamcorper aliquet elementum. Nulla sagittis, ante eu consequat varius, urna tortor auctor ante, vitae imperdiet tellus lacus sit amet est. Vivamus luctus hendrerit lacus, ut suscipit augue ornare eu. Proin aliquam elit ac gravida rhoncus.`;

}
